// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.3
// source: protos/grp1.proto

package grp1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Grp1_StdRpc_FullMethodName     = "/grp1.Grp1/StdRpc"
	Grp1_ExampleRpc_FullMethodName = "/grp1.Grp1/ExampleRpc"
)

// Grp1Client is the client API for Grp1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Grp1Client interface {
	StdRpc(ctx context.Context, in *StdAsk, opts ...grpc.CallOption) (*StdRet, error)
	ExampleRpc(ctx context.Context, in *ExampleReq, opts ...grpc.CallOption) (*ExampleResp, error)
}

type grp1Client struct {
	cc grpc.ClientConnInterface
}

func NewGrp1Client(cc grpc.ClientConnInterface) Grp1Client {
	return &grp1Client{cc}
}

func (c *grp1Client) StdRpc(ctx context.Context, in *StdAsk, opts ...grpc.CallOption) (*StdRet, error) {
	out := new(StdRet)
	err := c.cc.Invoke(ctx, Grp1_StdRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grp1Client) ExampleRpc(ctx context.Context, in *ExampleReq, opts ...grpc.CallOption) (*ExampleResp, error) {
	out := new(ExampleResp)
	err := c.cc.Invoke(ctx, Grp1_ExampleRpc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Grp1Server is the server API for Grp1 service.
// All implementations must embed UnimplementedGrp1Server
// for forward compatibility
type Grp1Server interface {
	StdRpc(context.Context, *StdAsk) (*StdRet, error)
	ExampleRpc(context.Context, *ExampleReq) (*ExampleResp, error)
	mustEmbedUnimplementedGrp1Server()
}

// UnimplementedGrp1Server must be embedded to have forward compatible implementations.
type UnimplementedGrp1Server struct {
}

func (UnimplementedGrp1Server) StdRpc(context.Context, *StdAsk) (*StdRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StdRpc not implemented")
}
func (UnimplementedGrp1Server) ExampleRpc(context.Context, *ExampleReq) (*ExampleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExampleRpc not implemented")
}
func (UnimplementedGrp1Server) mustEmbedUnimplementedGrp1Server() {}

// UnsafeGrp1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Grp1Server will
// result in compilation errors.
type UnsafeGrp1Server interface {
	mustEmbedUnimplementedGrp1Server()
}

func RegisterGrp1Server(s grpc.ServiceRegistrar, srv Grp1Server) {
	s.RegisterService(&Grp1_ServiceDesc, srv)
}

func _Grp1_StdRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StdAsk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Grp1Server).StdRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grp1_StdRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Grp1Server).StdRpc(ctx, req.(*StdAsk))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grp1_ExampleRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Grp1Server).ExampleRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grp1_ExampleRpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Grp1Server).ExampleRpc(ctx, req.(*ExampleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Grp1_ServiceDesc is the grpc.ServiceDesc for Grp1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grp1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grp1.Grp1",
	HandlerType: (*Grp1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StdRpc",
			Handler:    _Grp1_StdRpc_Handler,
		},
		{
			MethodName: "ExampleRpc",
			Handler:    _Grp1_ExampleRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/grp1.proto",
}
