// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.11.3
// source: protos/grp1.proto

package grp1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StdAsk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AskName       string                 `protobuf:"bytes,1,opt,name=AskName,proto3" json:"AskName,omitempty"`
	AskStr        string                 `protobuf:"bytes,2,opt,name=AskStr,proto3" json:"AskStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdAsk) Reset() {
	*x = StdAsk{}
	mi := &file_protos_grp1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdAsk) ProtoMessage() {}

func (x *StdAsk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdAsk.ProtoReflect.Descriptor instead.
func (*StdAsk) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{0}
}

func (x *StdAsk) GetAskName() string {
	if x != nil {
		return x.AskName
	}
	return ""
}

func (x *StdAsk) GetAskStr() string {
	if x != nil {
		return x.AskStr
	}
	return ""
}

type StdRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetSta        string                 `protobuf:"bytes,1,opt,name=RetSta,proto3" json:"RetSta,omitempty"`
	RetStr        string                 `protobuf:"bytes,2,opt,name=RetStr,proto3" json:"RetStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdRet) Reset() {
	*x = StdRet{}
	mi := &file_protos_grp1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdRet) ProtoMessage() {}

func (x *StdRet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdRet.ProtoReflect.Descriptor instead.
func (*StdRet) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{1}
}

func (x *StdRet) GetRetSta() string {
	if x != nil {
		return x.RetSta
	}
	return ""
}

func (x *StdRet) GetRetStr() string {
	if x != nil {
		return x.RetStr
	}
	return ""
}

type ExampleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqStr        string                 `protobuf:"bytes,1,opt,name=ReqStr,proto3" json:"ReqStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleReq) Reset() {
	*x = ExampleReq{}
	mi := &file_protos_grp1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleReq) ProtoMessage() {}

func (x *ExampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleReq.ProtoReflect.Descriptor instead.
func (*ExampleReq) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleReq) GetReqStr() string {
	if x != nil {
		return x.ReqStr
	}
	return ""
}

type ExampleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RespStr       string                 `protobuf:"bytes,1,opt,name=RespStr,proto3" json:"RespStr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleResp) Reset() {
	*x = ExampleResp{}
	mi := &file_protos_grp1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResp) ProtoMessage() {}

func (x *ExampleResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResp.ProtoReflect.Descriptor instead.
func (*ExampleResp) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{3}
}

func (x *ExampleResp) GetRespStr() string {
	if x != nil {
		return x.RespStr
	}
	return ""
}

var File_protos_grp1_proto protoreflect.FileDescriptor

const file_protos_grp1_proto_rawDesc = "" +
	"\n" +
	"\x11protos/grp1.proto\x12\x04grp1\":\n" +
	"\x06StdAsk\x12\x18\n" +
	"\aAskName\x18\x01 \x01(\tR\aAskName\x12\x16\n" +
	"\x06AskStr\x18\x02 \x01(\tR\x06AskStr\"8\n" +
	"\x06StdRet\x12\x16\n" +
	"\x06RetSta\x18\x01 \x01(\tR\x06RetSta\x12\x16\n" +
	"\x06RetStr\x18\x02 \x01(\tR\x06RetStr\"$\n" +
	"\n" +
	"ExampleReq\x12\x16\n" +
	"\x06ReqStr\x18\x01 \x01(\tR\x06ReqStr\"'\n" +
	"\vExampleResp\x12\x18\n" +
	"\aRespStr\x18\x01 \x01(\tR\aRespStr2c\n" +
	"\x04Grp1\x12&\n" +
	"\x06StdRpc\x12\f.grp1.StdAsk\x1a\f.grp1.StdRet\"\x00\x123\n" +
	"\n" +
	"ExampleRpc\x12\x10.grp1.ExampleReq\x1a\x11.grp1.ExampleResp\"\x00B+Z)github.com/dabory/abango-rest/protos;grp1b\x06proto3"

var (
	file_protos_grp1_proto_rawDescOnce sync.Once
	file_protos_grp1_proto_rawDescData []byte
)

func file_protos_grp1_proto_rawDescGZIP() []byte {
	file_protos_grp1_proto_rawDescOnce.Do(func() {
		file_protos_grp1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_grp1_proto_rawDesc), len(file_protos_grp1_proto_rawDesc)))
	})
	return file_protos_grp1_proto_rawDescData
}

var file_protos_grp1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_grp1_proto_goTypes = []any{
	(*StdAsk)(nil),      // 0: grp1.StdAsk
	(*StdRet)(nil),      // 1: grp1.StdRet
	(*ExampleReq)(nil),  // 2: grp1.ExampleReq
	(*ExampleResp)(nil), // 3: grp1.ExampleResp
}
var file_protos_grp1_proto_depIdxs = []int32{
	0, // 0: grp1.Grp1.StdRpc:input_type -> grp1.StdAsk
	2, // 1: grp1.Grp1.ExampleRpc:input_type -> grp1.ExampleReq
	1, // 2: grp1.Grp1.StdRpc:output_type -> grp1.StdRet
	3, // 3: grp1.Grp1.ExampleRpc:output_type -> grp1.ExampleResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_grp1_proto_init() }
func file_protos_grp1_proto_init() {
	if File_protos_grp1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_grp1_proto_rawDesc), len(file_protos_grp1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_grp1_proto_goTypes,
		DependencyIndexes: file_protos_grp1_proto_depIdxs,
		MessageInfos:      file_protos_grp1_proto_msgTypes,
	}.Build()
	File_protos_grp1_proto = out.File
	file_protos_grp1_proto_goTypes = nil
	file_protos_grp1_proto_depIdxs = nil
}
