// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.11.3
// source: protos/grp1.proto

package grp1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StdAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AskName string `protobuf:"bytes,1,opt,name=AskName,proto3" json:"AskName,omitempty"`
	AskStr  string `protobuf:"bytes,2,opt,name=AskStr,proto3" json:"AskStr,omitempty"`
}

func (x *StdAsk) Reset() {
	*x = StdAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grp1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StdAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdAsk) ProtoMessage() {}

func (x *StdAsk) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdAsk.ProtoReflect.Descriptor instead.
func (*StdAsk) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{0}
}

func (x *StdAsk) GetAskName() string {
	if x != nil {
		return x.AskName
	}
	return ""
}

func (x *StdAsk) GetAskStr() string {
	if x != nil {
		return x.AskStr
	}
	return ""
}

type StdRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetSta string `protobuf:"bytes,1,opt,name=RetSta,proto3" json:"RetSta,omitempty"`
	RetStr string `protobuf:"bytes,2,opt,name=RetStr,proto3" json:"RetStr,omitempty"`
}

func (x *StdRet) Reset() {
	*x = StdRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grp1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StdRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdRet) ProtoMessage() {}

func (x *StdRet) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdRet.ProtoReflect.Descriptor instead.
func (*StdRet) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{1}
}

func (x *StdRet) GetRetSta() string {
	if x != nil {
		return x.RetSta
	}
	return ""
}

func (x *StdRet) GetRetStr() string {
	if x != nil {
		return x.RetStr
	}
	return ""
}

type ExampleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqStr string `protobuf:"bytes,1,opt,name=ReqStr,proto3" json:"ReqStr,omitempty"`
}

func (x *ExampleReq) Reset() {
	*x = ExampleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grp1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleReq) ProtoMessage() {}

func (x *ExampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleReq.ProtoReflect.Descriptor instead.
func (*ExampleReq) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleReq) GetReqStr() string {
	if x != nil {
		return x.ReqStr
	}
	return ""
}

type ExampleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespStr string `protobuf:"bytes,1,opt,name=RespStr,proto3" json:"RespStr,omitempty"`
}

func (x *ExampleResp) Reset() {
	*x = ExampleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_grp1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResp) ProtoMessage() {}

func (x *ExampleResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_grp1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResp.ProtoReflect.Descriptor instead.
func (*ExampleResp) Descriptor() ([]byte, []int) {
	return file_protos_grp1_proto_rawDescGZIP(), []int{3}
}

func (x *ExampleResp) GetRespStr() string {
	if x != nil {
		return x.RespStr
	}
	return ""
}

var File_protos_grp1_proto protoreflect.FileDescriptor

var file_protos_grp1_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x31, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74, 0x64,
	0x41, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x73, 0x6b, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x73, 0x6b, 0x53, 0x74, 0x72, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x52, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x53, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x74, 0x53, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x53, 0x74,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x74, 0x53, 0x74, 0x72, 0x22,
	0x24, 0x0a, 0x0a, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x71, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52,
	0x65, 0x71, 0x53, 0x74, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x72, 0x32, 0x63,
	0x0a, 0x04, 0x47, 0x72, 0x70, 0x31, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x52, 0x70, 0x63,
	0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x31, 0x2e, 0x53, 0x74, 0x64, 0x41, 0x73, 0x6b, 0x1a, 0x0c,
	0x2e, 0x67, 0x72, 0x70, 0x31, 0x2e, 0x53, 0x74, 0x64, 0x52, 0x65, 0x74, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x0a, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x70, 0x63, 0x12, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x67, 0x72, 0x70, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x61, 0x62, 0x6f, 0x72, 0x79, 0x2f, 0x61, 0x62, 0x61, 0x6e, 0x67, 0x6f, 0x2d,
	0x72, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b, 0x67, 0x72, 0x70, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_grp1_proto_rawDescOnce sync.Once
	file_protos_grp1_proto_rawDescData = file_protos_grp1_proto_rawDesc
)

func file_protos_grp1_proto_rawDescGZIP() []byte {
	file_protos_grp1_proto_rawDescOnce.Do(func() {
		file_protos_grp1_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_grp1_proto_rawDescData)
	})
	return file_protos_grp1_proto_rawDescData
}

var file_protos_grp1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_grp1_proto_goTypes = []any{
	(*StdAsk)(nil),      // 0: grp1.StdAsk
	(*StdRet)(nil),      // 1: grp1.StdRet
	(*ExampleReq)(nil),  // 2: grp1.ExampleReq
	(*ExampleResp)(nil), // 3: grp1.ExampleResp
}
var file_protos_grp1_proto_depIdxs = []int32{
	0, // 0: grp1.Grp1.StdRpc:input_type -> grp1.StdAsk
	2, // 1: grp1.Grp1.ExampleRpc:input_type -> grp1.ExampleReq
	1, // 2: grp1.Grp1.StdRpc:output_type -> grp1.StdRet
	3, // 3: grp1.Grp1.ExampleRpc:output_type -> grp1.ExampleResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_grp1_proto_init() }
func file_protos_grp1_proto_init() {
	if File_protos_grp1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_grp1_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StdAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_grp1_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StdRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_grp1_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ExampleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_grp1_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExampleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_grp1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_grp1_proto_goTypes,
		DependencyIndexes: file_protos_grp1_proto_depIdxs,
		MessageInfos:      file_protos_grp1_proto_msgTypes,
	}.Build()
	File_protos_grp1_proto = out.File
	file_protos_grp1_proto_rawDesc = nil
	file_protos_grp1_proto_goTypes = nil
	file_protos_grp1_proto_depIdxs = nil
}
